{% set name = "opentelemetry-instrumentation-fastapi" %}
{% set version = "0.27b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-fastapi-{{ version }}.tar.gz
  sha256: b21e42e18492ca496d5d2d89ec3c1eb9260f4dc911f1270c66c1c78ea9b29b0a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.27b0
    - opentelemetry-instrumentation-asgi ==0.27b0
    - opentelemetry-semantic-conventions ==0.27b0
    - opentelemetry-util-http ==0.27b0
    - python >=3.6
    # - requests ~=2.23.0
    # - opentelemetry-test ==0.24b0
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.26b1
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.27b0
    # - fastapi ~=0.58

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-fastapi
  summary: OpenTelemetry FastAPI Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
