{% set name = "opentelemetry-instrumentation-fastapi" %}
{% set version = "0.33b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-fastapi-{{ version }}.tar.gz
  sha256: e859fdfba57b340f2d8fd0c79e6f2c70a5323eb05af72107944a4698134db957

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.33b0
    - opentelemetry-instrumentation-asgi ==0.33b0
    - opentelemetry-semantic-conventions ==0.33b0
    - opentelemetry-util-http ==0.33b0
    - python >=3.6
    # - requests ~=2.23.0
    # - opentelemetry-test ==0.24b0
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.26b1
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.27b0
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.28b0
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.28b1
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.29b0
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.30b0
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.30b1
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.31b0
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.32b0
    # - fastapi ~=0.58
    # - requests ~=2.23.0
    # - opentelemetry-test-utils ==0.33b0
    # - fastapi ~=0.58

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-fastapi
  summary: OpenTelemetry FastAPI Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
